relativeURLs = true
googleAnalytics = "G-EWF7HKXD39"
title = "Antoine Germain"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
baseURL = "https://antoine-germain.github.io/"

[author]
name = "Antoine Germain"

[params]
title = "F.R.S.- F.N.R.S."
institution = "CORE/LIDAM, UCLouvain"
logo = "my_face_small.webp"
Twitter = "ant1germain"
Email = "antoine.germain@uclouvain.be"
